name: Docker Build And Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

    
jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          sudo docker build -t cms-fe .

      - name: Stop and remove old container
        run: |
          sudo docker stop cms-fe || echo "No container to stop"
          sudo docker rm cms-fe || echo "No container to remove"

      - name: Run new container
        run: |
          sudo docker run --restart always --name cms-fe -d -p 3117:3117 cms-fe
